// Generated by CoffeeScript 1.3.3
(function() {
  var f, factorial;

  f = function(n) {
    if (n <= 1) {
      return 1;
    } else {
      return n + f(n - 1);
    }
  };

  factorial = function(n) {
    var i, r, _i;
    r = 0;
    for (i = _i = 0; _i < 100000; i = ++_i) {
      r = f(n);
    }
    return r;
  };

  exports.factorial = factorial;

}).call(this);
