// Generated by CoffeeScript 1.3.3
(function() {
  var factorial;

  factorial = function(n) {
    if (n <= 1) {
      return 1;
    } else {
      return n + factorial(n - 1);
    }
  };

  exports.factorial = factorial;

}).call(this);
