// Generated by CoffeeScript 1.3.3
(function() {
  var HelloWorldJs;

  HelloWorldJs = (function() {

    function HelloWorldJs() {
      this.m_count = 0;
    }

    HelloWorldJs.prototype.hello = function() {
      this.m_count++;
      return "Hello World";
    };

    return HelloWorldJs;

  })();

  exports.HelloWorldJs = HelloWorldJs;

}).call(this);
