// Generated by CoffeeScript 1.3.3
(function() {
  var LOOP, NUMBER, doneFn, factorial_cc, factorial_eio, factorial_js, i, loopFn, utils, _i, _j, _k, _results;

  factorial_js = require("./factorial_js");

  factorial_cc = require("./factorial_cc");

  factorial_eio = require("./factorial_eio");

  utils = require("./utils");

  NUMBER = 5000;

  LOOP = 100000;

  console.time("C++ Time: ");

  for (i = _i = 0; 0 <= LOOP ? _i < LOOP : _i > LOOP; i = 0 <= LOOP ? ++_i : --_i) {
    factorial_cc.factorial(NUMBER);
  }

  console.timeEnd("C++ Time: ");

  console.time("JavaScript Time: ");

  for (i = _j = 0; 0 <= LOOP ? _j < LOOP : _j > LOOP; i = 0 <= LOOP ? ++_j : --_j) {
    factorial_js.factorial(NUMBER);
  }

  console.timeEnd("JavaScript Time: ");

  loopFn = function(v, i, iterFn) {
    return factorial_eio.factorial(NUMBER, iterFn);
  };

  doneFn = function() {
    return console.timeEnd("C++ Async Real Time: ");
  };

  console.time("C++ Async Time: ");

  console.time("C++ Async Real Time: ");

  utils.asyncParForEach((function() {
    _results = [];
    for (var _k = 0; 0 <= LOOP ? _k < LOOP : _k > LOOP; 0 <= LOOP ? _k++ : _k--){ _results.push(_k); }
    return _results;
  }).apply(this), loopFn, doneFn);

  console.timeEnd("C++ Async Time: ");

}).call(this);
