// Generated by CoffeeScript 1.3.3
(function() {
  var LOOP, NUMBER, factorial_js, utils;

  factorial_js = require("./factorial_js");

  utils = require("./utils");

  NUMBER = 5000;

  LOOP = 100000;

  console.time("JavaScript Time: ");

  factorial_js.factorial(NUMBER);

  console.timeEnd("JavaScript Time: ");

}).call(this);
