// Generated by CoffeeScript 1.3.3
(function() {
  var FN, LOOP, NUMBER, factorial_cc, factorial_eio, factorial_js, i, _i, _j, _k;

  factorial_js = require("./factorial_js");

  factorial_cc = require("./factorial_cc");

  factorial_eio = require("./factorial_eio");

  NUMBER = 5000;

  LOOP = 100000;

  FN = function() {};

  console.time("JavaScript Time: ");

  for (i = _i = 0; 0 <= LOOP ? _i < LOOP : _i > LOOP; i = 0 <= LOOP ? ++_i : --_i) {
    factorial_js.factorial(NUMBER);
  }

  console.log("JavaScript Result: " + (factorial_js.factorial(NUMBER)));

  console.timeEnd("JavaScript Time: ");

  console.time("C++ Time: ");

  for (i = _j = 0; 0 <= LOOP ? _j < LOOP : _j > LOOP; i = 0 <= LOOP ? ++_j : --_j) {
    factorial_cc.factorial(NUMBER);
  }

  console.log("C++ Result: " + (factorial_cc.factorial(NUMBER)));

  console.timeEnd("C++ Time: ");

  console.time("C++ Async Time: ");

  factorial_eio.factorial(NUMBER, function(result) {
    return console.log("C++ Async Result: " + result);
  });

  for (i = _k = 0; 0 <= LOOP ? _k < LOOP : _k > LOOP; i = 0 <= LOOP ? ++_k : --_k) {
    factorial_eio.factorial(NUMBER, FN);
  }

  console.timeEnd("C++ Async Time: ");

}).call(this);
